import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import { Container, Flex } from '@chakra-ui/react'

import LayoutProvider from '@/components/LayoutProvider'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

interface IRootLayout {
  children: ReactNode
}

const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wincrate',
  description: 'Generated by Wincrate',
}

const RootLayout = ({ children }: Readonly<IRootLayout>) => (
  <html lang="en">
    <body className={urbanist.className}>
      <LayoutProvider>
        <Header />
        <main>
          <Container maxW={'container.xl'}>
            <Flex justifyContent="center">{children}</Flex>
          </Container>
        </main>
        <Footer />
      </LayoutProvider>
    </body>
  </html>
)

export default RootLayout
